In [89]:
import pandas as pd
from hnmchallenge.data_reader import DataReader
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from hnmchallenge.models.top_pop import TopPop
from hnmchallenge.evaluation.python_evaluation import map_at_k
from hnmchallenge.constant import *
from hnmchallenge.models.sgmc.sgmc import SGMC
from hnmchallenge.models.ease.ease import EASE
from hnmchallenge.models.itemknn.itemknn import ItemKNN 

In [90]:
import logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

In [91]:
dataset = Dataset()
dr = DataReader()

In [111]:
a = np.array([1,2,3,4,5,6,7])
b, c = np.array_split(a, 2)

In [113]:
b

array([1, 2, 3, 4])

In [99]:
fd = dr.get_filtered_full_data()

In [104]:
fd.sample(frac=1).reset_index(drop=True)

t_dat  customer_id  article_id     price  sales_channel_id
0        2019-10-03       282774        3432  0.015000                 1
1        2020-04-23       685064       10629  0.049729                 2
2        2020-08-14       820257        7992  0.022017                 1
3        2019-08-27       194423        3099  0.010153                 1
4        2019-06-26       568664        2513  0.022017                 2
...             ...          ...         ...       ...               ...
14361083 2020-02-12       233200        3855  0.020695                 1
14361084 2018-09-28        28768         302  0.013542                 1
14361085 2020-08-02       244057         415  0.016932                 2
14361086 2019-09-05       234864        4663  0.080797                 2
14361087 2019-05-29       527431          41  0.016932                 1

[14361088 rows x 5 columns]

In [103]:
len(ff)

31788324

In [101]:
len(fd)

14361088

In [51]:
item_last_month = fd[fd["t_dat"] >= "2020-09-1"][DEFAULT_ITEM_COL].unique()

In [88]:
len(dataset.get_black_list_item())

78295

In [47]:
len(item_last_month)

18684

In [80]:
item_last_month = dr.get_item_last_month()

In [82]:
ar = np.arange(dataset._ARTICLES_NUM)

In [84]:
len(ar[~np.isin(ar, item_last_month)])

78295

In [85]:
len(ar)

104547

In [68]:
a = np.ones((5,10))

In [69]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
a[np.isin(a, [0,3])]

array([], dtype=float64)

In [75]:
a[~((a == [0,3]).all())]

/tmp/ipykernel_27233/1861391791.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a[~((a == [0,3]).all())]


AttributeError: 'bool' object has no attribute 'all'

In [71]:
np.arange(a.shape[1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np

In [66]:
a[:, [0,3]] = -1

In [67]:
a

array([[-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [53]:
test_item = dataset.get_test_df()[[DEFAULT_ITEM_COL]].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [49]:
len(test_item)

18684

In [50]:
len(test_item.intersection(set(item_last_month)))

18684

In [92]:
tr = dr.get_transactions()

In [93]:
len(tr[DEFAULT_USER_COL].unique())

1362281

In [23]:
len(tr[tr["t_dat"] >= "2020-09-1"])

453926

In [95]:
item_last_month = (tr[tr["t_dat"] >= "2020-09-1"][DEFAULT_ITEM_COL].unique())

In [98]:
len(tr[tr[DEFAULT_ITEM_COL].isin(item_last_month)][DEFAULT_USER_COL].unique())

1136206

In [21]:
item_last_month = tr[tr["t_dat"] >= "2020-09-1"][DEFAULT_ITEM_COL].unique()

In [20]:
len(item_last_month)

32716

In [10]:
tr["t_dat"].max()

'2020-09-22'

In [14]:
test_item = set(tr[tr["t_dat"]>"2020-09-14"][DEFAULT_ITEM_COL].unique())

In [18]:
len(test_item)

18684

In [15]:
ss = set(item_last_month)

In [17]:
len(ss.intersection(test_item))

18684

In [10]:
test_item = set(dataset.get_test_df()[DEFAULT_ITEM_COL].unique())
len(dataset.get_test_df()[DEFAULT_ITEM_COL].unique())

18684

In [11]:
val_item = set(dataset.get_val_df()[DEFAULT_ITEM_COL].unique())
len(dataset.get_val_df()[DEFAULT_ITEM_COL].unique())

18674

In [13]:
len(val_item.intersection(test_item))

14275

In [14]:
fd = dr.get_full_data()

In [36]:
fd["t_dat"].max()

Timestamp('2020-09-22 00:00:00')

In [53]:
sub = fd[fd["t_dat"] >= "2020-09-1"]

In [58]:
item_sub = sub[DEFAULT_ITEM_COL].unique()

In [59]:
item_sub

array([76029, 74943, 98045, ..., 97634, 57641, 82271])

In [63]:
len(fd)

31788324

In [62]:
len(fd[fd[DEFAULT_ITEM_COL].isin(item_sub)])

16020504

In [67]:
len(fd[DEFAULT_USER_COL].unique())

1362281

In [66]:
len(fd[fd[DEFAULT_ITEM_COL].isin(item_sub)][DEFAULT_USER_COL].unique())

1167050

In [60]:
item_sub = set(sub[DEFAULT_ITEM_COL].unique())
len(sub[DEFAULT_ITEM_COL].unique())

26252

In [55]:
len(item_sub.intersection(val_item))

18674

In [56]:
len(item_sub.intersection(test_item))

18684